project_id = "pukcbqfjzswqmjkhwzfk"

[functions.processar-ficha-v2]
verify_jwt = false

[functions.notificar-ficha-whatsapp]
verify_jwt = false

[functions.transcrever-audio]
verify_jwt = false

[functions.salvar-ficha]
verify_jwt = false

[functions.criar-cliente]
verify_jwt = false
