// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdvncahkwfmcywwqlopl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdm5jYWhrd2ZtY3l3d3Fsb3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Njc4NTQsImV4cCI6MjA3MzU0Mzg1NH0.TOwusRBrbIDTkUkGToaKp06Hs2kK07Ejb_HLC2099yY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});